services:
  backend:
    image: quotes-back
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "8080:80"
    env_file:
      - .env
    restart: always
    deploy:
       resources:
        limits:
          cpus: '2'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 200M
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health"]
      interval: 10s
      timeout: 10s
      retries: 3
     
  postgres:
    image: bitnami/postgresql
    env_file:
      - .env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    
volumes:
  postgres-data:

