services:
  backend:
    image: quotes-back
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "8080:80"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=quotes
  postgres:
    image: bitnami/postgresql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=quotes
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:

