name: Main Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  security-events: write
  actions: read
  attestations: read
  checks: read
  deployments: read
  discussions: read
  issues: read
  packages: read
  pages: read
  pull-requests: read
  repository-projects: read
  statuses: read
  id-token: write

jobs:
  build:
    name: Build python dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build
        uses: ./.github/workflows/build
   
  scanners:
    name: Run Security Scanners
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Trivy Workflow
        uses: ./.github/workflows/trivy

      - name: Run Scorecard Workflow
        uses: ./.github/workflows/scorecard

      - name: Run Bandit Workflow
        uses: ./.github/workflows/bandit
