name: Main Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  security-events: write
  actions: read
  attestations: read
  checks: read
  deployments: read
  discussions: read
  issues: read
  packages: read
  pages: read
  pull-requests: read
  repository-projects: read
  statuses: read
  id-token: write

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yml

  security:
    needs: build
    name: Security Scans
    uses: ./.github/workflows/security_scans.yml

  deploy:
    needs: build
    name: Deploy
    uses: ./.github/workflows/deploy.yml